apiVersion: v1
kind: Service
metadata:
  name: abctech-service
spec:
  type: NodePort
  selector:
    app: abctech
  ports:
    - port: 80          # External service port
      targetPort: 8080  # Container port (Tomcat)
      nodePort: 30080   # Optional fixed NodePort
