# Source: retail-store-sample-ui-chart/templates/configmap.yml
apiVersion: v1
kind: ConfigMap
metadata:
  name: ui
  namespace: ui
data:
  RETAIL_UI_ENDPOINTS_CATALOG: http://catalog.catalog
  RETAIL_UI_ENDPOINTS_CARTS: http://carts.cart
  RETAIL_UI_ENDPOINTS_CHECKOUT: http://checkout.checkout
  RETAIL_UI_ENDPOINTS_ORDERS: http://orders.order
